/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4ca582b5-2460-4866-9a92-924f4ff1a73f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_RdepsnEGS",
    "aws_user_pools_web_client_id": "700n4to9pt90e7qhv5fcs10ap8",
    "oauth": {}
};


export default awsmobile;
